In [20]:
LED_METER_DENSITY = 144.0/1000.0 #leds/m

# pitch
MIN_PIXEL_PITCH = 1
MAX_PIXEL_PITCH  = 14
STEP_PIXEL_PITCH = 1
DEFAULT_PIXEL_PITCH = 7

# mass
MIN_STRIP_MASS = 22
MAX_STRIP_MASS = 220
STEP_STRIP_MASS = 1
DEFAULT_STRIP_MASS = 22

# angular speed 
MIN_ANGULAR_SPEED = 150
MAX_ANGULAR_SPEED = 330 
STEP_ANGULAR_SPEED = 1
DEFAULT_ANGULAR_SPEED = 225

# hole width
MIN_HOLE_RADIUS = 189/2.0 # 205.782cm
MAX_HOLE_RADIUS = MIN_HOLE_RADIUS * 3.0 #cm
STEP_HOLE_RADIUS = 1
DEFAULT_HOLE_RADIUS = 189/2.0

MIN_VERTICAL_RESOLUTION = 31 # 220
MAX_VERTICAL_RESOLUTION = MIN_VERTICAL_RESOLUTION + 77
 

# strip length
MIN_TOP_ROPE_LENGTH_OFFSET = 0
MAX_TOP_ROPE_LENGTH_OFFSET = 30 * DEFAULT_PIXEL_PITCH
STEP_TOP_ROPE_LENGTH_OFFSET = DEFAULT_PIXEL_PITCH
DEFAULT_TOP_ROPE_LENGTH_OFFSET = 3 * DEFAULT_PIXEL_PITCH


# strip length
MIN_ROPE_LENGTH = MIN_VERTICAL_RESOLUTION * DEFAULT_PIXEL_PITCH
MAX_ROPE_LENGTH = MAX_VERTICAL_RESOLUTION * DEFAULT_PIXEL_PITCH
STEP_ROPE_LENGTH = DEFAULT_PIXEL_PITCH
DEFAULT_ROPE_LENGTH = MIN_ROPE_LENGTH

# strip height
MIN_POLE_HEIGHT = 200
MAX_POLE_HEIGHT = MIN_POLE_HEIGHT + 43 * DEFAULT_PIXEL_PITCH
STEP_POLE_HEIGHT = DEFAULT_PIXEL_PITCH
DEFAULT_POLE_HEIGHT = MIN_POLE_HEIGHT


In [25]:
import troposkein
import pandas as pd
import numpy as np
from mystats import statistics
import math
from tqdm.notebook import tqdm

speed_factors = np.arange(MIN_ANGULAR_SPEED, MAX_ANGULAR_SPEED + 1, 1)
display(speed_factors)
length_factors = np.arange(MIN_ROPE_LENGTH, MAX_ROPE_LENGTH + 1, 1)
display(length_factors)
height_factors = np.arange(MIN_POLE_HEIGHT, MAX_POLE_HEIGHT + 1, 1)
display(height_factors)

columns = ['height', 'length', 'width', 'horizontal_resolution']
df_models = pd.DataFrame(columns=columns)

with tqdm(total= len(height_factors)  * len(length_factors), desc="Processing frame directories", unit="directory") as pbar:
        for pole_height in height_factors:
            for rope_length in length_factors:
                if rope_length > pole_height:
                    est_curve_x, est_curve_y, max_diameter, max_vertical_resolution, max_horizontal_resolution, central_tension, extremity_tension =  troposkein.troposkein2D(
                        150, 
                        rope_length, 
                        pole_height, 
                        DEFAULT_HOLE_RADIUS, 
                        DEFAULT_STRIP_MASS, 
                        DEFAULT_PIXEL_PITCH, 
                        DEFAULT_TOP_ROPE_LENGTH_OFFSET, 
                        verbose=False
                    )

                    new_row = pd.DataFrame({
                        'height': [pole_height], 
                        'length': [rope_length], 
                        'width': [max_diameter], 
                        'horizontal_resolution':[max_horizontal_resolution]
                        })
                    df_models = pd.concat([df_models, new_row], ignore_index=True)
                pbar.update(1)

display(df_models)
df_models.to_pickle('../results/model.pkl')
# init_length_pixels = 31
# length_pixels = np.array([0, 15, 31, 46, 62, 77]) 
# pixel_pitch = 7
# length_pixels += init_length_pixels
# length_values = length_pixels * pixel_pitch
# strip_factors = np.array([1, 2, 3, 4])
# NB_GROUP = len(speed_factors) * len(strip_factors)
# display(df_curves)

array([150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
       189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
       202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214,
       215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
       228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
       241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
       254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
       267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279,
       280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,
       293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305,
       306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318,
       319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 33

array([217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
       256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281,
       282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294,
       295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307,
       308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320,
       321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333,
       334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346,
       347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359,
       360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372,
       373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385,
       386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 39

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 38

Processing frame directories:   0%|          | 0/163080 [00:00<?, ?directory/s]

height length       width horizontal_resolution
0         200    217  265.188864                   119
1         200    218  267.513954                   120
2         200    219  269.784693                   121
3         200    220  272.005293                   122
4         200    221  274.180206                   123
...       ...    ...         ...                   ...
122320    501    752  706.375833                   317
122321    501    753  707.651295                   317
122322    501    754  708.925186                   318
122323    501    755  710.196768                   318
122324    501    756   711.46982                   319

[122325 rows x 4 columns]